# Generated by Django 4.2.5 on 2023-09-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('report_text', models.TextField()),
                ('overall_future_value', models.IntegerField()),
                ('hitting_grade', models.IntegerField()),
                ('power_grade', models.IntegerField()),
                ('running_grade', models.IntegerField()),
                ('fielding_grade', models.IntegerField()),
                ('throwing_grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PitcherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('report_text', models.TextField()),
                ('overall_future_value', models.IntegerField()),
                ('pitch_grade', models.IntegerField()),
                ('pitch_velocity', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='battingstatistics',
            name='player',
        ),
        migrations.DeleteModel(
            name='NewsArticle',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.DeleteModel(
            name='BattingStatistics',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
